#!/bin/sh

rm -rf assets/*

mkdir -p assets

for i in `find renders -type f -iname d\*.png`; do
	regular="`echo $i | sed 's/renders/assets/g'`"
	regularselected="`echo $i | sed 's/renders/assets/g' \
		| sed 's/.png/-selected.png/g'`"
	twotime="`echo $i | sed 's/renders/assets/g' \
		| sed 's/.png/@2x.png/g'`"
	twotimeselected="`echo $i | sed 's/renders/assets/g' \
		| sed 's/.png/-selected@2x.png/g'`"
	convert -resize 64x -filter Lanczos "$i" "$regular"
	convert -resize 128x -filter Lanczos "$i" "$twotime"
	convert -channel A -blur 8 \
		-channel RGB -modulate 0,0 \
		-channel R -brightness-contrast 100 \
		-channel A -gamma 2 \
		-channel A -brightness-contrast 25,50 \
		"$regular" "$regularselected"
	convert -channel A -blur 16 \
		-channel RGB -modulate 0,0 \
		-channel R -brightness-contrast 100 \
		-channel A -gamma 4 \
		-channel A -brightness-contrast 25,50 \
		"$twotime" "$twotimeselected"
done

cd assets

for file in buttonNormal buttonPushed questionMark; do
	cp ../assetssrc/$file.png $file@2x.png
	convert -resize 50%x50% $file@2x.png $file.png
done

cp ../renders/background.png background@2x.png
convert -resize 50%x50% background@2x.png background.png
