#!/bin/sh

rm -rf assets/*

for i in `find renders -type f -iname d\*.png`; do
	regular="`echo $i | sed 's/renders/assets/g'`"
	regularselected="`echo $i | sed 's/renders/assets/g' \
		| sed 's/.png/-selected.png/g'`"
	twotime="`echo $i | sed 's/renders/assets/g' \
		| sed 's/.png/@2x.png/g'`"
	twotimeselected="`echo $i | sed 's/renders/assets/g' \
		| sed 's/.png/-selected@2x.png/g'`"
	convert -resize 64x -filter Lanczos "$i" "$regular"
	convert -resize 128x -filter Lanczos "$i" "$twotime"
	convert -channel A -blur 8 \
		-channel RGB -modulate 0,0 \
		-channel R -brightness-contrast 100 \
		-channel A -gamma 2 \
		-channel A -brightness-contrast 25,50 \
		"$regular" "$regularselected"
	convert -channel A -blur 16 \
		-channel RGB -modulate 0,0 \
		-channel R -brightness-contrast 100 \
		-channel A -gamma 2 \
		-channel A -brightness-contrast 25,50 \
		"$twotime" "$twotimeselected"
done

cd assets

convert -resize 32x ../renders/d6-6.png roll-top.png
convert -resize 64x ../renders/d6-6.png roll-top@2x.png
convert -channel A -blur 8 \
	-channel RGB -modulate 0,0 \
	-channel R -brightness-contrast 100 \
	-channel A -gamma 2 \
	-channel A -brightness-contrast 25,50 \
	roll-top.png roll-selected.png
convert -channel A -blur 16 \
	-channel RGB -modulate 0,0 \
	-channel R -brightness-contrast 100 \
	-channel A -gamma 2 \
	-channel A -brightness-contrast 25,50 \
	roll-top@2x.png roll-selected@2x.png
composite -compose atop roll-top.png roll-selected.png roll.png
composite -compose atop roll-top@2x.png roll-selected@2x.png roll@2x.png
cp roll-top.png reset.png
cp roll-top@2x.png reset@2x.png
rm roll-top.png roll-selected.png
rm roll-top@2x.png roll-selected@2x.png

cp ../renders/background.png background@2x.png
convert -resize "50%x50%" -filter Lanczos background@2x.png background.png
