#!/bin/bash

mkdir -p icons

cd icons

rm -rf ./*

FILE=../renders/iTunesArtwork.png

function mkIcon {
	convert -filter Lanczos -resize "$1" "$2" "$3";
}

mkIcon "57x57" "$FILE" "Icon.png"
mkIcon "72x72" "$FILE" "Icon-72.png"
mkIcon "114x114" "$FILE" "Icon@2x.png"
mkIcon "120x120" "$FILE" "Icon-120@2x.png"
mkIcon "29x29" "$FILE" "Icon-Small.png"
mkIcon "50x50" "$FILE" "Icon-Small-50.png"
mkIcon "58x58" "$FILE" "Icon-Small@2x.png"
