#!/bin/bash

OUT='iTunesArtwork-covered.png'
rm -f $OUT

FILE=renders/iTunesArtwork.png
COVER=assetssrc/iconcover.png

function mkIcon {
	convert -filter Lanczos -resize "$1" "$2" "$3.tmp.png";
	convert -filter Lanczos -resize "$1" "$COVER" "$3.cover.png";
	composite -compose atop "$3.cover.png" "$3.tmp.png" "$3";
	rm "$3.tmp.png" "$3.cover.png";
}

mkIcon "1024x1024" "$FILE" "$OUT"
